services:
  database:
    image: postgres:17
    restart: always
    env_file:
      - ./.env
    volumes:
      - database_data:/var/lib/postgresql/data

  web:
    build: .
    command: uvicorn src:app --host 0.0.0.0 --port 8000 --reload
    restart: always
    volumes:
      - .:/src
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - database

volumes:
  database_data: