services:
  database:
    image: postgres:17
    restart: always
    env_file:
      - ./.env
    volumes:
      - database_data:/var/lib/postgresql/data

  elasticsearch:
    image: elasticsearch:8.15.4
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node

  kibana:
    image: kibana:8.15.4
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  filebeat:
    build:
      context: ./filebeat
    container_name: filebeat
    volumes:
      - ./fastapi-logs:/app/logs
    depends_on:
      - elasticsearch
      - kibana

  web:
    build: .
    command: uvicorn src:app --host 0.0.0.0 --port 8000 --reload
    restart: always
    volumes:
      - ./src
      - ./fastapi-logs:/app/logs
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - database
      - elasticsearch

volumes:
  database_data:
  elasticsearch_data:
    driver: local