"""unique

Revision ID: e8d0b6e2c60b
Revises: 29f6ddd9ddee
Create Date: 2024-10-27 00:28:29.319186

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e8d0b6e2c60b"
down_revision: Union[str, None] = "29f6ddd9ddee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("orderitems_order_id_key", "orderitems", type_="unique")
    op.create_unique_constraint(None, "orderitems", ["order_id", "product_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "orderitems", type_="unique")
    op.create_unique_constraint(
        "orderitems_order_id_key", "orderitems", ["order_id"]
    )
    # ### end Alembic commands ###
