"""add index

Revision ID: 7a108fe31809
Revises: e8d0b6e2c60b
Create Date: 2024-11-01 23:41:46.068452

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7a108fe31809"
down_revision: Union[str, None] = "e8d0b6e2c60b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_orderitems_id"), "orderitems", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_orderitems_order_id"),
        "orderitems",
        ["order_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_orderitems_product_id"),
        "orderitems",
        ["product_id"],
        unique=False,
    )
    op.create_index(op.f("ix_orders_id"), "orders", ["id"], unique=False)
    op.create_index(op.f("ix_products_id"), "products", ["id"], unique=False)
    op.create_index(
        op.f("ix_products_quantity"), "products", ["quantity"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_products_quantity"), table_name="products")
    op.drop_index(op.f("ix_products_id"), table_name="products")
    op.drop_index(op.f("ix_orders_id"), table_name="orders")
    op.drop_index(op.f("ix_orderitems_product_id"), table_name="orderitems")
    op.drop_index(op.f("ix_orderitems_order_id"), table_name="orderitems")
    op.drop_index(op.f("ix_orderitems_id"), table_name="orderitems")
    # ### end Alembic commands ###
