"""unique

Revision ID: e91f6ba0fb56
Revises: 619ad0077bc0
Create Date: 2024-10-26 22:47:25.289927

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e91f6ba0fb56"
down_revision: Union[str, None] = "619ad0077bc0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "orderitems", ["order_id"])
    op.create_unique_constraint(None, "orderitems", ["product_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "orderitems", type_="unique")
    op.drop_constraint(None, "orderitems", type_="unique")
    # ### end Alembic commands ###
