"""unique

Revision ID: 29f6ddd9ddee
Revises: e91f6ba0fb56
Create Date: 2024-10-26 22:57:20.048716

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "29f6ddd9ddee"
down_revision: Union[str, None] = "e91f6ba0fb56"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "orderitems_product_id_key", "orderitems", type_="unique"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "orderitems_product_id_key", "orderitems", ["product_id"]
    )
    # ### end Alembic commands ###
