"""Update Table

Revision ID: 0fff0350d629
Revises: 8b5edf88a679
Create Date: 2024-11-09 01:04:32.485295

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0fff0350d629"
down_revision: Union[str, None] = "8b5edf88a679"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_constraint("users_name_key", "users", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("users_name_key", "users", ["name"])
    op.alter_column(
        "users", "name", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
