"""add index

Revision ID: 7993daf2b310
Revises: 7a108fe31809
Create Date: 2024-11-01 23:58:12.015098

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7993daf2b310"
down_revision: Union[str, None] = "7a108fe31809"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_orderitems_id", table_name="orderitems")
    op.drop_index("ix_orderitems_order_id", table_name="orderitems")
    op.drop_index("ix_orderitems_product_id", table_name="orderitems")
    op.drop_index("ix_orders_id", table_name="orders")
    op.drop_index("ix_products_id", table_name="products")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_products_id", "products", ["id"], unique=False)
    op.create_index("ix_orders_id", "orders", ["id"], unique=False)
    op.create_index(
        "ix_orderitems_product_id", "orderitems", ["product_id"], unique=False
    )
    op.create_index(
        "ix_orderitems_order_id", "orderitems", ["order_id"], unique=False
    )
    op.create_index("ix_orderitems_id", "orderitems", ["id"], unique=False)
    # ### end Alembic commands ###
