"""empty message

Revision ID: 974c33a3a39d
Revises: 0fff0350d629
Create Date: 2024-11-10 22:50:40.330674

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "974c33a3a39d"
down_revision: Union[str, None] = "0fff0350d629"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("user_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        None, "orders", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "orders", type_="foreignkey")
    op.drop_column("orders", "user_id")
    # ### end Alembic commands ###
